### ISSUE TITLE
two or more checks on same argument

### ISSUE THREAD

**Issue by 3-16** [davidgtonge/backbone_query#13]
I am building my querys dynamically. Therefore It would be great if backbone_query had the ability to check two or more times on the same argument. Meaning that these are the same:

```
MyCollection.query({ likes: {$gte:5}, likes: {$lte:15} });

MyCollection.query({ likes: {$between:[5,15} });
```

I can´t get it to work. This does not work either:

```
MyCollection.query({
  $and:{
    likes: {$gte: 5 }, 
    likes: {$lte: 15 }
}});
```

**Comment by davidgtonge** [comment]
Hi, you can use an array rather than an object to get this behaviour.
I don't have time to test the code, but you should be able to do something like this:

``` javascript
MyCollection.query([
{ likes: {$gte:5} }, 
{ likes: {$lte:15} }
]);

```

**Comment by 3-16** [comment]
Thank you that works great!
