### ISSUE TITLE
Implement benchmark.js?

### ISSUE THREAD

**Issue by pocesar** [davidgtonge/backbone_query#17]
It would be nice to have an out-of-the-box benchmark to run using `node benchmarks.js` using Benchmark.js. 

I'm using this library on a AngularJS project and angularjs is known of firing the same cycles over and over again, just one page load, a $watcher is called 90 times! 

so I'm interested to I can rest assured that this won't ever be a bottleneck.

**Comment by davidgtonge** [comment]
Good, idea. I've been re-writing a lot of the library and will push the updated version live shortly.
I've been doing quite a few tests via jsperf.com, but I'll add in a performance cli script.
